# Generated by Django 4.1.7 on 2023-03-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=255)),
                ('library_layout', models.CharField(max_length=6)),
                ('library_source', models.CharField(max_length=100)),
                ('feature_table_path', models.TextField()),
                ('taxonomy_results_path', models.TextField()),
            ],
        ),
    ]
