# Generated by Django 4.1.7 on 2023-03-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='study_id',
        ),
        migrations.AlterField(
            model_name='study',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='study',
            name='library_layout',
            field=models.CharField(max_length=100),
        ),
    ]
